const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');const root=path.join(__dirname,'../public');let count=0;
function env(stored='{}',blocked=false){let es=new Map(),timers=new Map(),id=0;class E{constructor(){this.children=[];this.dataset={};this.style={};this.disabled=false;this.className='';this.events={};this.classList={contains:k=>this.className.split(' ').includes(k),add:(...ks)=>this.className=[...new Set([...this.className.split(' '),...ks])].join(' '),remove:k=>this.className=this.className.split(' ').filter(x=>x!==k).join(' '),toggle:(k,on)=>on?this.classList.add(k):this.classList.remove(k)}}set innerHTML(v){this.html=v;this.children=[];for(let m of v.matchAll(/id="([^"]+)"/g))es.set(m[1],new E)}get innerHTML(){return this.html}appendChild(e){this.children.push(e)}setAttribute(){}focus(){}addEventListener(k,f){this.events[k]=f}click(){if(!this.disabled){this.events.click?.();this.onclick?.call(this)}}}
let get=k=>{if(!es.has(k))es.set(k,new E);return es.get(k)};for(let m of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/id="([^"]+)"/g))get(m[1]);let screens=[...es].filter(([k])=>k.startsWith('screen-')).map(([,v])=>v),lines=['5050','hint','swap'].map(k=>{let e=new E;e.dataset.lifeline=k;return e});
let document={body:{dataset:{}},getElementById:get,createElement:()=>new E,addEventListener(){},querySelector:get,querySelectorAll:s=>s==='.screen'?screens:s==='.lifeline'?lines:s==='.answer-btn'?get('answers').children:[]};let c={window:{scrollTo(){},addEventListener(){}},document,console,localStorage:{getItem(){if(blocked)throw Error();return stored},setItem(k,v){if(blocked)throw Error();stored=v}},setTimeout:f=>{timers.set(++id,f);return id},clearTimeout:i=>timers.delete(i),FormData:class{},location:{},alert(){}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'data.js'),'utf8'),c);let a=fs.readFileSync(path.join(root,'app.js'),'utf8').replace('  state.sound=persist.sound','  window.test={state,startGame,prepareQuestion,pickQuestion,answer,useLifeline,showScreen,beginPhase,getPersist:()=>persist};\n  state.sound=persist.sound');vm.runInContext(a,c);c.window.test.state.sound=false;return {api:c.window.test,bank:c.window.QUESTION_BANK,get,flush(){let f=[...timers.values()];timers.clear();f.forEach(fn=>fn())},screen:k=>get(k).classList.contains('active')};}
function test(n,f){f();count++;console.log('PASS',n)}function reply(e,ok=true){let i=e.api.state.renderedOptions.findIndex(o=>o.correct===ok);e.api.answer(i,e.get('answers').children[i]);e.flush()}
test('79 valid unique questions and sufficient phase pools',()=>{let e=env();assert.equal(e.bank.length,79);assert.equal(new Set(e.bank.map(q=>q.id)).size,79);for(let q of e.bank){assert.equal(new Set(q.options).size,4);assert.match(q.correct,/^[ABCD]$/);assert.ok(q.hint&&q.source&&q.question)}for(let p=1;p<=5;p++)assert.ok(e.bank.filter(q=>q.phase===p).length>=8)});
test('Correct shuffled mapping for all 79 questions',()=>{let e=env();for(let q of e.bank){e.api.startGame();e.api.beginPhase();e.api.state.phase=q.phase;e.api.prepareQuestion(q);reply(e);assert.equal(e.api.state.phaseScore,1);assert.equal(e.api.state.lives,3)}});
test('25 correct answers, five badges and final victory',()=>{let e=env();e.api.startGame();e.api.beginPhase();for(let p=1;p<=5;p++){for(let i=0;i<5;i++){reply(e);e.get('nextBtn').click()}assert.ok(e.screen('screen-phase-result'));assert.equal(e.api.getPersist().highestBadge,p);e.get('continuePhaseBtn').click();if(p<5){assert.ok(e.screen('screen-phase-intro'));e.api.beginPhase()}}assert.ok(e.screen('screen-victory'));assert.equal(e.api.state.totalCorrect,25);assert.ok(e.api.getPersist().everCompleted)});
test('Third error ends game, previous correct answers retained',()=>{let e=env();e.api.startGame();e.api.beginPhase();reply(e);e.get('nextBtn').click();for(let i=0;i<3;i++){reply(e,false);e.get('nextBtn').click()}assert.ok(e.screen('screen-gameover'));assert.equal(e.api.state.lives,0);assert.equal(e.api.state.phaseScore,1)});
test('50:50 removes two wrong options only',()=>{let e=env();e.api.startGame();e.api.beginPhase();e.api.useLifeline('5050');let removed=e.get('answers').children.filter(b=>b.classList.contains('removed'));assert.equal(removed.length,2);for(let b of removed)assert.equal(e.api.state.renderedOptions[b.dataset.index].correct,false);e.api.useLifeline('hint');assert.ok(e.api.state.jokers.hint)});
test('Swap preserves score and prevents a second joker',()=>{let e=env();e.api.startGame();e.api.beginPhase();let id=e.api.state.current.id;e.api.useLifeline('swap');assert.notEqual(e.api.state.current.id,id);e.api.useLifeline('hint');assert.ok(e.api.state.jokers.hint);assert.equal(e.api.state.usedThisQuestion,true);assert.equal(e.api.state.lives,3)});
test('Hint content, one use per game and restart reset',()=>{let e=env();e.api.startGame();e.api.beginPhase();e.api.useLifeline('hint');assert.equal(e.get('hintText').textContent,e.api.state.current.hint);reply(e);e.get('nextBtn').click();assert.equal(e.api.state.jokers.hint,false);e.api.startGame();e.api.beginPhase();assert.ok(Object.values(e.api.state.jokers).every(Boolean))});
test('No repeated questions within phase',()=>{let e=env();e.api.startGame();e.api.beginPhase();let ids=new Set([e.api.state.current.id]);for(let i=0;i<7;i++){e.api.prepareQuestion(e.api.pickQuestion());assert.ok(!ids.has(e.api.state.current.id));ids.add(e.api.state.current.id)}});
test('Double click counts only once',()=>{let e=env();e.api.startGame();e.api.beginPhase();let i=e.api.state.renderedOptions.findIndex(o=>o.correct),b=e.get('answers').children[i];e.api.answer(i,b);e.api.answer(i,b);e.flush();assert.equal(e.api.state.phaseScore,1)});
test('Leaving game cancels pending answer',()=>{let e=env();e.api.startGame();e.api.beginPhase();let i=e.api.state.renderedOptions.findIndex(o=>o.correct);e.api.answer(i,e.get('answers').children[i]);e.api.showScreen('screen-home');e.flush();assert.equal(e.api.state.phaseScore,0)});
test('Menu cannot consume jokers',()=>{let e=env();e.api.useLifeline('swap');assert.ok(e.api.state.jokers.swap)});
test('Corrupt or blocked localStorage cannot stop play',()=>{for(let s of ['null','bad','{"history":null,"discovered":false}','{"games":"x"}']){let e=env(s);e.api.startGame();e.api.beginPhase();reply(e);assert.equal(e.api.state.totalCorrect,1)}let e=env('{}',true);e.api.startGame();e.api.beginPhase();reply(e);assert.equal(e.api.state.totalCorrect,1)});
test('PWA manifest, icons and offline shell are complete',()=>{let m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');assert.ok(m.icons.some(i=>i.sizes==='192x192'));assert.ok(m.icons.some(i=>i.sizes==='512x512'&&i.purpose==='maskable'));for(let i of m.icons)assert.ok(fs.statSync(path.join(root,i.src)).size>1000);let sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');for(let f of ['index.html','styles.css','data.js','app.js','cover.webp','fase-5.webp'])assert.ok(sw.includes(f));});
console.log(count+' suites passed (logic; does not verify browser layout).');
